### ISSUE TITLE
Improve user experience with examples

### ISSUE THREAD

**Issue by Mixaster995** [networkservicemesh/deployments-k8s#2673] opened 2021-08-18 11:22 UTC
## Description
Remove unnecessary bash scripts where it is possible and move more things into files to improve user experience with examples.

**Comment by denis-tingaikin** [comment] 2022-01-20 23:44
I don't see any bash scripts. I think the issue is outdated and I don't see any link on the problematic place. So closing.

**Closed by denis-tingaikin** 2022-01-20 23:44 UTC
Labels: performance
