### ISSUE TITLE
Missing log printouts in forwarder-vpp at DEBUG log level 

### ISSUE THREAD

**Issue by ljkiraly** [networkservicemesh/deployments-k8s#9242] opened 2023-06-20 14:16 UTC
## Expected Behavior

Log printout is expected in forwarder-vpp logs at DEBUG log level.

## Current Behavior

Setting log level to DEBUG the log printouts after "Startup completed in ..." printout are missing.

## Failure Information (for bugs)

At TRACE log level any debug log printout can be seen in forwarder-vpp logs. For example printouts reporting netlink and vpp API operations regarding connection setup.

## Steps to Reproduce

1. Set NSM_LOG_LEVEL to DEBUG value in apps/forwarder-vpp/forwarder.yaml
1. Start any basic use-case (e.g. Kernel2Ethernet2Kernel)
2. Check the logs of forwarder-vpp

## Context

* NSM Version: 1.9.0.

## Example
Comparing the forwarder debug level printouts in case of TRACE and DEBUG log level:
[trace-level-forwarder-vpp-log.txt](https://github.com/networkservicemesh/deployments-k8s/files/11801829/trace-level-forwarder-vpp-log.txt)
[debug-level-forwarder-vpp-log.txt](https://github.com/networkservicemesh/deployments-k8s/files/11801859/debug-level-forwarder-vpp-log.txt)
> grep DEBU trace-level-forwarder-vpp-log.txt | wc -l
69
 > grep DEBU debug-level-forwarder-vpp-log.txt | wc -l
19

**Comment by ljkiraly** [comment] 2023-06-20 14:38
Can be related to https://github.com/networkservicemesh/deployments-k8s/issues/9124

**Comment by ljkiraly** [comment] 2023-06-28 09:59
> Can be related to #9124

It is not related. It is present from v1.4.0, when` log.EnableTracing(level == logrus.TraceLevel)` was introduced.

**Comment by denis-tingaikin** [comment] 2023-07-18 10:57
@ljkiraly The problem should be fixed by https://github.com/networkservicemesh/sdk/pull/1489

Latest main is available for testing.
Also, v1.10.0 will include the fix.

Feel free to reopen the ticket if the problem is still reproduciable.

Thanks for the pointing this problem we really appreciate any reports ;)

**Closed by denis-tingaikin** 2023-07-18 10:57 UTC
Labels: bug
