### ISSUE TITLE
Issue running nse-composition example

### ISSUE THREAD

**Issue by damiankopyto** [networkservicemesh/deployments-k8s#2381] opened 2021-07-30 15:54 UTC
Hello, I am trying the NSM with the nse-composition example but the NSM environment seems to be unstable. The client (nsc-kernel) is stuck in CrashLoopBackOff (with error "cannot support any of the requested mechanism") most of the time, and therefore is not able to ping the endpoint. Other components are also restarting (sometimes with OOM Kill status).

**Environment:**
Ubuntu 20.04 and RHEL 8.4 (tried with both)
K8s v1.21.0
NSM - main branch -557750d1d6e7469bf1deb10c9ec46be68b725cd7
This is a single node deployment (not sure if it could make a difference)

**Steps to reproduce:**
1. Set up spire as per: [examples/spire](https://github.com/networkservicemesh/deployments-k8s/tree/main/examples/spire)
2. Set up example/basic : [examples/basic]( https://github.com/networkservicemesh/deployments-k8s/tree/main/examples/basic)
3. Set up the nse-composition as per: [features/nse-composition](https://github.com/networkservicemesh/deployments-k8s/tree/main/examples/features/nse-composition)
4. Try to ping endpoint from client and check the status/logs of the pods.

**Pod status:**
````
# kubectl get pods -n ns-m4gf5
NAME                                 READY   STATUS             RESTARTS   AGE  
nsc-kernel-7ff64d979b-lj8ss          0/1     CrashLoopBackOff   10         37m  
nse-firewall-vpp-75c664447-f5bmt     1/1     Running            0          37m  
nse-kernel-67b499bc4d-257ts          2/2     Running            4          37m
nse-passthrough-1-79dcc5ff4-p44lc    1/1     Running            3          37m
nse-passthrough-2-5db868d789-vczv7   1/1     Running            6          37m
nse-passthrough-3-6794587c84-5jpdc   1/1     Running            5          37m
````

```
#  kubectl get pods -n nsm-system
NAME                                     READY   STATUS    RESTARTS   AGE
admission-webhook-k8s-698974c59b-xdlrz   1/1     Running   0          40m
forwarder-vpp-srlbd                      1/1     Running   8          40m
nsmgr-mf8th                              1/1     Running   12         40m
registry-k8s-758587b875-md2w6            1/1     Running   1          40m
```

```
# kubectl get networkservices -n nsm-system
NAME              AGE
nse-composition   38m
```

The NSE and NSC pods do not receive the nsm interface:
```
# kubectl exec ${NSE} -n ${NAMESPACE} -- ip addr
Defaulted container "nse" out of: nse, nginx
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
3: eth0@if37: <BROADCAST,MULTICAST,UP,LOWER_UP,M-DOWN> mtu 1450 qdisc noqueue state UP
    link/ether da:18:f7:11:0a:f9 brd ff:ff:ff:ff:ff:ff
    inet 10.244.0.28/24 brd 10.244.0.255 scope global eth0
       valid_lft forever preferred_lft forever

kubectl exec ${NSC} -n ${NAMESPACE} -- ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
3: eth0@if38: <BROADCAST,MULTICAST,UP,LOWER_UP,M-DOWN> mtu 1450 qdisc noqueue state UP
    link/ether 5e:d4:29:cb:ef:3a brd ff:ff:ff:ff:ff:ff
    inet 10.244.0.29/24 brd 10.244.0.255 scope global eth0
       valid_lft forever preferred_lft forever

```

As can be seen from output above and the logs attached, the Client pod keeps failing to connect to the manager. Do you have any thoughts on what could be causing this issue?
[forwarder-vpp.LOG](https://github.com/networkservicemesh/deployments-k8s/files/6908623/forwarder-vpp.LOG)
[nsc-kernel.LOG](https://github.com/networkservicemesh/deployments-k8s/files/6908625/nsc-kernel.LOG)
[nsmgr.LOG](https://github.com/networkservicemesh/deployments-k8s/files/6908626/nsmgr.LOG)

**Comment by edwarnicke** [comment] 2021-07-31 02:44
@Mixaster995 Could you have a look?

**Comment by Mixaster995** [comment] 2021-08-09 07:52
@damiankopyto thanks for your report. 
Could you, please, provide additional information: 
- are you testing this locally on kind or somwhere else?
- what are your system configuration (memory, cpu, etc.)?
- could you, please, provide additional logs for all components of this example(nsc, nse, passthrough1,2,3, firewall, forwarder, nsmgr) and also previous logs (result of 
`kubectl logs --previous`)

**Comment by Mixaster995** [comment] 2021-08-10 09:58
Retested this case on kind 1.21. 
Tested with different resources: 4 cpus and 2,4,6,8gb memory
Provided errors with CrashLoopBackOff never occurred. With 2gb or less memory cluster not working(it is expected behaviour).
@damiankopyto, please add some additional info to recreate this issue.

**Comment by damiankopyto** [comment] 2021-08-10 12:11
Hi @Mixaster995 
Sorry for late response I needed to recreate my environment
- I am testing locally, on a baremetal server.
- Ubuntu 20.04, 500GB+ RAM, 128 CPUs (HT-on)
- Attaching the logs for current/previous logs for all components (some of the did not have previous logs) in the zip file.
- I have accidentally deployed on K8s v1.20.0 this time but I see the same issue, let me know if I should do with v1.21.0 again.
- Also I have noticed now that the 2M hugepages have been enabled by default by the OS could this cause issue?
````
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.2 LTS
Release:        20.04
Codename:       focal
--------------------------------------------------------------
$ cat /proc/cmdline
BOOT_IMAGE=/vmlinuz-5.4.0-65-generic root=/dev/mapper/ubuntu--vg-ubuntu--lv ro
--------------------------------------------------------------
$ cat /proc/meminfo
MemTotal:       **527675592 kB**
MemFree:        493493840 kB
MemAvailable:   516295508 kB
Buffers:         1225912 kB
Cached:         23325044 kB
SwapCached:            0 kB
Active:          9788248 kB
Inactive:       18300960 kB
Active(anon):    2786740 kB
Inactive(anon):  1365248 kB
Active(file):    7001508 kB
Inactive(file): 16935712 kB
Unevictable:       36840 kB
Mlocked:           36840 kB
SwapTotal:             0 kB
SwapFree:              0 kB
Dirty:             17992 kB
Writeback:             0 kB
AnonPages:       3573956 kB
Mapped:          2968988 kB
Shmem:           1387808 kB
KReclaimable:    2284920 kB
Slab:            4741744 kB
SReclaimable:    2284920 kB
SUnreclaim:      2456824 kB
KernelStack:       91008 kB
PageTables:        59208 kB
NFS_Unstable:          0 kB
Bounce:                0 kB
WritebackTmp:          0 kB
CommitLimit:    263706724 kB
Committed_AS:   40672192 kB
VmallocTotal:   34359738367 kB
VmallocUsed:      374996 kB
VmallocChunk:          0 kB
Percpu:           350720 kB
HardwareCorrupted:     0 kB
AnonHugePages:     90112 kB
ShmemHugePages:        0 kB
ShmemPmdMapped:        0 kB
FileHugePages:         0 kB
FilePmdMapped:         0 kB
CmaTotal:              0 kB
CmaFree:               0 kB
HugePages_Total:     **128**
HugePages_Free:      128
HugePages_Rsvd:        0
HugePages_Surp:        0
Hugepagesize:       2048 kB
Hugetlb:          262144 kB
DirectMap4k:     1818560 kB
DirectMap2M:    28948480 kB
DirectMap1G:    507510784 kB
-------------------------------------------------------------------
# lscpu
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   46 bits physical, 57 bits virtual
CPU(s):                          128
On-line CPU(s) list:             0-127
Thread(s) per core:              2
Core(s) per socket:              32
-------------------------------------------------------------------

````

[nsm-logs.zip](https://github.com/networkservicemesh/deployments-k8s/files/6961462/nsm-logs.zip)

Thanks for looking into this

**Comment by Mixaster995** [comment] 2021-08-11 08:41
After some tests it seems like it's related to problem with spire restarts:  https://github.com/networkservicemesh/deployments-k8s/issues/2393
@damiankopyto could you, please, retest this after this problem will be fixed.

**Comment by damiankopyto** [comment] 2021-08-11 10:29
@Mixaster995 Sure will do, do you know the rough timeline for a fix?
Just on the topic of the spire restarts, I do not see my spire pods restarting, is the spire restart something internal within the spire pod that does not affect the life of the pod?

```
$ kubectl get pod -n spire
NAME                    READY   STATUS    RESTARTS   AGE
pod/spire-agent-sqh64   1/1     Running   0          23h
pod/spire-server-0      1/1     Running   0          23h
```

**Comment by jkossak** [comment] 2021-09-01 07:42
Hi @edwarnicke @Mixaster995 have you made any progress on this issue? Are you going to provide a fix to eliminate the restarts errors from nsm-system pods and the example pods? If yes when I can expect it roughly?

**Comment by Mixaster995** [comment] 2021-09-06 04:47
Hi @jkossak. Thank you for very detailed description, it is really helpful. I've just returned from PTO and continued investigating this issue and will provide the answers as soon as possible.

**Comment by jkossak** [comment] 2021-09-06 15:42
Hi @Mixaster995 , thank you for getting back to me. Great to hear you are working on it. 

Just to add some more info about this issue, here is the output of dmesg:

[dmesg.txt](https://github.com/networkservicemesh/deployments-k8s/files/7116723/dmesg.txt)

Today I tried the example again after pulling the latest changes. All worked for about  10 minutes (despite few restarts of nsc-kernel and nsmgr at the begininng). Then nse-passthrough-1 and nse-passthrough-2 got into OOMKiller error and can't get back to life staying most of the time in CrashLoopBackOff,. They start only for a few seconds to be killed again.

One question I have: I don't see the pods with vpp using hugepages. Aren't hugepages required to run VPP operations?

**Comment by Mixaster995** [comment] 2021-09-09 11:46
Hi @jkossak, hugepages not required for VPP to work - it's working fine without it. AFAIK, it is might be needed for some specific features, but we not using those.

**Comment by edwarnicke** [comment] 2021-09-09 13:29
@jkossak VPP *can* use hugepages.  If VPP *can't* get hugepages, it will log a very nasty message and keep on working to the best of its ability.

**Comment by jkossak** [comment] 2021-09-09 14:05
Thank you @edwarnicke and @Mixaster995 for answering my question, so this message I am seeing is actually expected and normal:
```
vpp[21]: buffer: numa[0] falling back to non-hugepage backed buffer pool (vlib_physmem_shared_map_create: pmalloc_map_pages: Unable to lock pages: Cannot allocate memory)
```

**Comment by jkossak** [comment] 2021-09-13 16:39
Hi @edwarnicke, @Mixaster995 , I increased the value of the NSM_REQUEST_TIMEOUT environment variable to 160s , but it was already set to 75s by default in examples/features/nse-composition/patch-nsc.yaml 

I still  observe the instability of the cross-connection that breaks after 2 - 3 minutes, and resumes from time to time for another couple of minutes. 

The pods after few minutes:
```
ns-49p5k      nsc-kernel-6d8db46cc9-h4j74                                 1/1     Running     1          19m
ns-49p5k      nse-firewall-vpp-66646d5c97-2tsqt                           1/1     Running     0          19m
ns-49p5k      nse-kernel-7db68697d5-w6r6r                                 2/2     Running     1          19m
ns-49p5k      nse-passthrough-1-679b46b87f-bqxpx                          1/1     Running     0          19m
ns-49p5k      nse-passthrough-2-6f59968558-tqtcr                          1/1     Running     1          19m
ns-49p5k      nse-passthrough-3-6c89477d58-zt5f4                          1/1     Running     0          19m
nsm-system    admission-webhook-k8s-55799cd7f9-swnbr                      1/1     Running     0          21m
nsm-system    forwarder-vpp-hq7wb                                         1/1     Running     0          21m
nsm-system    nsmgr-4rg8h                                                 1/1     Running     0          21m
nsm-system    registry-k8s-6f7f46c897-v7f5p                               1/1     Running     0          21m
 ```

**Comment by Mixaster995** [comment] 2021-09-13 18:59
Hi, @jkossak. We found possible source of the problem - with some logic turned off wrong behaviour doesn't occur anymore. Now trying to find the solution for this parts.

**Comment by jkossak** [comment] 2021-09-14 09:32
Thank you @Mixaster995 for letting me know.

**Comment by Mixaster995** [comment] 2021-09-16 09:27
Hi, @jkossak.
Could you, please, try nse-composition example with images i've prepared:
https://hub.docker.com/r/mixaster95/forwarder for forwarder-vpp
https://hub.docker.com/r/mixaster95/firewall for nse-firewall-vpp, passthrough-1, passthrough-2, passthrough-3

It would be great, if you let me know if everything is ok or if there is still instability/errors. Thank you.

**Comment by jkossak** [comment] 2021-09-16 10:41
Thanks @Mixaster995 , I will try the example with the new images today and let you know how it goes then.

**Comment by jkossak** [comment] 2021-09-16 14:22
Hi @Mixaster995, I steel see the pods crashing.
```
ns-xnz7h      nsc-kernel-596bdf89b4-rdt8j                                 0/1     Error       3          4m40s
ns-xnz7h      nse-firewall-vpp-6fc568b55b-n76tx                           1/1     Running     0          4m40s
ns-xnz7h      nse-kernel-647564b8c6-d4txr                                 2/2     Running     2          4m40s
ns-xnz7h      nse-passthrough-1-6dbbdbfd57-qqbsq                          1/1     Running     0          4m40s
ns-xnz7h      nse-passthrough-2-85cd6f4cdb-9xf98                          1/1     Running     0          4m40s
ns-xnz7h      nse-passthrough-3-65cdd5cf47-tgjqz                          1/1     Running     0          4m40s
nsm-system    admission-webhook-k8s-5c4f9c9d6d-sm4gs                      1/1     Running     0          6m20s
nsm-system    forwarder-vpp-7bm64                                         1/1     Running     0          6m20s
nsm-system    nsmgr-dx9dg                                                 0/1     Running     4          6m20s
nsm-system    registry-k8s-5446d9b464-6mlxw                               1/1     Running     0          6m20s

```

The cross connection breaks even faster:

```sh
$ kubectl exec ${NSC} -n ${NAMESPACE} -- ping  172.16.1.100
PING 172.16.1.100 (172.16.1.100): 56 data bytes
64 bytes from 172.16.1.100: seq=0 ttl=64 time=93.116 ms
64 bytes from 172.16.1.100: seq=1 ttl=64 time=93.013 ms
64 bytes from 172.16.1.100: seq=2 ttl=64 time=88.954 ms
64 bytes from 172.16.1.100: seq=3 ttl=64 time=120.871 ms
64 bytes from 172.16.1.100: seq=4 ttl=64 time=112.742 ms
64 bytes from 172.16.1.100: seq=5 ttl=64 time=120.646 ms
64 bytes from 172.16.1.100: seq=6 ttl=64 time=120.537 ms
64 bytes from 172.16.1.100: seq=7 ttl=64 time=88.467 ms
64 bytes from 172.16.1.100: seq=8 ttl=64 time=104.360 ms
64 bytes from 172.16.1.100: seq=9 ttl=64 time=100.245 ms
64 bytes from 172.16.1.100: seq=10 ttl=64 time=112.144 ms
64 bytes from 172.16.1.100: seq=11 ttl=64 time=120.108 ms
64 bytes from 172.16.1.100: seq=12 ttl=64 time=115.971 ms
64 bytes from 172.16.1.100: seq=13 ttl=64 time=95.897 ms
64 bytes from 172.16.1.100: seq=14 ttl=64 time=103.794 ms
64 bytes from 172.16.1.100: seq=15 ttl=64 time=235.731 ms
64 bytes from 172.16.1.100: seq=16 ttl=64 time=91.633 ms
64 bytes from 172.16.1.100: seq=17 ttl=64 time=107.529 ms
64 bytes from 172.16.1.100: seq=18 ttl=64 time=131.353 ms
64 bytes from 172.16.1.100: seq=19 ttl=64 time=147.232 ms
64 bytes from 172.16.1.100: seq=20 ttl=64 time=111.130 ms
64 bytes from 172.16.1.100: seq=21 ttl=64 time=143.064 ms
64 bytes from 172.16.1.100: seq=22 ttl=64 time=114.847 ms
command terminated with exit code 137

```

**Comment by edwarnicke** [comment] 2021-09-16 14:29
@Mixaster995 Could you provide images that simply disable directmemif for the moment for @jkossak  to try?

**Comment by jkossak** [comment] 2021-09-16 15:25
@Mixaster995, @denis-tingaikin, I increased nsmgr memory limit to 100Mi (from 60Mi) and all worked for 20 minutes. But started crashing again:

```
ns-776vj      nsc-kernel-596bdf89b4-dw6qp                                 1/1     Running     0          21m
ns-776vj      nse-firewall-vpp-6fc568b55b-84snl                           1/1     Running     0          21m
ns-776vj      nse-kernel-647564b8c6-nt9v2                                 2/2     Running     1          21m
ns-776vj      nse-passthrough-1-6dbbdbfd57-467gl                          1/1     Running     0          21m
ns-776vj      nse-passthrough-2-85cd6f4cdb-v4g8r                          1/1     Running     0          21m
ns-776vj      nse-passthrough-3-65cdd5cf47-xspdc                          1/1     Running     0          21m
nsm-system    admission-webhook-k8s-5c4f9c9d6d-xjmtk                      1/1     Running     0          22m
nsm-system    forwarder-vpp-frhnc                                         1/1     Running     0          22m
nsm-system    nsmgr-7jlhh                                                 1/1     Running     0          22m
nsm-system    registry-k8s-5446d9b464-gk8hr                               1/1     Running     0          22m
```

```
ns-776vj      nsc-kernel-596bdf89b4-dw6qp                                 1/1     Running     5          33m
ns-776vj      nse-firewall-vpp-6fc568b55b-84snl                           1/1     Running     1          33m
ns-776vj      nse-kernel-647564b8c6-nt9v2                                 2/2     Running     3          33m
ns-776vj      nse-passthrough-1-6dbbdbfd57-467gl                          1/1     Running     0          33m
ns-776vj      nse-passthrough-2-85cd6f4cdb-v4g8r                          1/1     Running     0          33m
ns-776vj      nse-passthrough-3-65cdd5cf47-xspdc                          1/1     Running     0          33m
nsm-system    admission-webhook-k8s-5c4f9c9d6d-xjmtk                      1/1     Running     0          35m
nsm-system    forwarder-vpp-frhnc                                         1/1     Running     0          35m
nsm-system    nsmgr-7jlhh                                                 1/1     Running     3          35m
```

I noticed nsmgr used memory is increasing starting from ~40 to:

```
NAME                                     CPU(cores)   MEMORY(bytes)
admission-webhook-k8s-5c4f9c9d6d-xjmtk   2m           17Mi
forwarder-vpp-frhnc                      207m         431Mi
nsmgr-7jlhh                              54m          93Mi
registry-k8s-5446d9b464-gk8hr            8m           24Mi

nsc-kernel-596bdf89b4-dw6qp          10m          11Mi
nse-firewall-vpp-6fc568b55b-84snl    215m         395Mi
nse-kernel-647564b8c6-nt9v2          1m           3Mi
nse-passthrough-1-6dbbdbfd57-467gl   224m         384Mi
nse-passthrough-2-85cd6f4cdb-v4g8r   213m         386Mi
nse-passthrough-3-65cdd5cf47-xspdc   233m         385Mi
```

Here are the nsmgr logs: 
[2.log](https://github.com/networkservicemesh/deployments-k8s/files/7179061/2.log)
[3.log](https://github.com/networkservicemesh/deployments-k8s/files/7179062/3.log)

**Comment by denis-tingaikin** [comment] 2021-09-16 16:23
Cannot find a reason for nsmgr restart. 
Did you use `-p` option on getting logs?

**Comment by jkossak** [comment] 2021-09-16 16:34
@denis-tingaikin, I took the logs again with -p `kubectl logs -f -p nsmgr-7jlhh -n nsm-system`

I wonder why the pod's memory increases always up to its limit - then kernel kills the process as it is shown by dmesg.

[dmesg.txt](https://github.com/networkservicemesh/deployments-k8s/files/7179481/dmesg.txt)
[nsmgrlogs.log](https://github.com/networkservicemesh/deployments-k8s/files/7179453/nsmgrlogs.log)

**Comment by edwarnicke** [comment] 2021-09-16 18:03
@Mixaster995 Question... how was the issue with nsmgr memory traced back to an issue with direct memif in the forwarder?
It is a counter intuitive root cause... curious the chain of reasoning.

**Comment by Bolodya1997** [comment] 2021-09-17 11:12
@jkossak 
Are you running tests each time restarting `spire` pods? If so, I suppose we have reproduced your issue locally and it is actually related to the same old issue https://github.com/networkservicemesh/deployments-k8s/issues/2393 which is not yet fully fixed :)

Can you please try one more time with the following images:
1. `nsc-kernel` - `rrandom312/cmd-nsc:rework-connect`.
2. `nsmgr` - `rrandom312/cmd-nsmgr:rework-connect`.
3. `forwarder-vpp` - `rrandom312/cmd-forwarder-vpp:rework-connect`.
4. `nse-firewall-vpp`, `passthrough-1`, `passthrough-2`, `passthrough-3` - `rrandom312/cmd-nse-firewall-vpp:rework-connect`.

All of these images start consuming slightly more RAM, so limits also need to be increased:
1. `nsc-kernel` -> `30Mi`.
2. `nsmgr` -> `80Mi`.
3. `nse-kernel` -> `30Mi`.

**Comment by Bolodya1997** [comment] 2021-09-17 11:22
@edwarnicke 
We actually have found several issues during our investigation:
1. `cmd-nse-firewall-vpp` heal leads to panic - https://github.com/networkservicemesh/cmd-nse-firewall-vpp/pull/62.
2. Direct memif works incorrect and leads to `up` client infinite waiting on refresh - https://github.com/networkservicemesh/sdk-vpp/pull/377.
3. Tokens become invalid after the SVID update on timeout - https://github.com/networkservicemesh/sdk/pull/1069.

Both [2, 3] issues forces some of hops to start sending Requests in infinite loop with little or zero timeout, so it increases RAM usage and so leads to OOM Killed pods.

We probably have some memory leaks in our code, I am currently trying to investigate if it is so.

**Comment by jkossak** [comment] 2021-09-17 12:05
Hi @Bolodya1997, before running the tests I always restart nsm-system pods,  and usually, I restart spire pods but not always. From my observation pods in the spire namespace behave stable (0 restarts) so some times I don't restart it and I encounter the same issues with nsmgr and other nsm pods.

I will run the example with the new images now, thanks.

**Comment by jkossak** [comment] 2021-09-17 12:43
@Bolodya1997, so far the example with the images you provided have been running over 20 minutes.  I do observe restarts of nsmgr after its termination (OOMKilled) but the cross-connection seems not to be broken.  There is no more restarts among other nsm pods.

```
ns-8rvkf      nsc-kernel-86b4bf5496-nzbxd                                 1/1     Running     0          21m
ns-8rvkf      nse-firewall-vpp-5d56554487-t4r6s                           1/1     Running     0          22m
ns-8rvkf      nse-kernel-65d77f9d59-6d2bg                                 2/2     Running     0          22m
ns-8rvkf      nse-passthrough-1-d774bdcd6-wx4qp                           1/1     Running     0          22m
ns-8rvkf      nse-passthrough-2-84d4b4ffbf-5mmfj                          1/1     Running     0          22m
ns-8rvkf      nse-passthrough-3-655b59cb64-fcmwk                          1/1     Running     0          22m
nsm-system    admission-webhook-k8s-5c4f9c9d6d-m2lsn                      1/1     Running     0          26m
nsm-system    forwarder-vpp-bh4hk                                         1/1     Running     0          26m
nsm-system    nsmgr-gxxlf                                                 1/1     Running     4          26m
nsm-system    registry-k8s-5446d9b464-ccsb4                               1/1     Running     0          26m
openness      nfd-release-node-feature-discovery-master-cc9d7b8f4-hvn9n   1/1     Running     0          11d
openness      nfd-release-node-feature-discovery-worker-s65vp             1/1     Running     0          11d
spire         spire-agent-4bchn                                           1/1     Running     0          21h
spire         spire-server-0                                              1/1     Running     0          21h
```

**Comment by jkossak** [comment] 2021-09-17 13:07
@Bolodya1997, after 27 minutes the cross connection stopped working, but the pods look like before:

```
ns-8rvkf      nsc-kernel-86b4bf5496-nzbxd                                 1/1     Running     0          46m
ns-8rvkf      nse-firewall-vpp-5d56554487-t4r6s                           1/1     Running     0          48m
ns-8rvkf      nse-kernel-65d77f9d59-6d2bg                                 2/2     Running     0          48m
ns-8rvkf      nse-passthrough-1-d774bdcd6-wx4qp                           1/1     Running     0          48m
ns-8rvkf      nse-passthrough-2-84d4b4ffbf-5mmfj                          1/1     Running     0          48m
ns-8rvkf      nse-passthrough-3-655b59cb64-fcmwk                          1/1     Running     0          48m
nsm-system    admission-webhook-k8s-5c4f9c9d6d-m2lsn                      1/1     Running     0          51m
nsm-system    forwarder-vpp-bh4hk                                         1/1     Running     0          51m
nsm-system    nsmgr-gxxlf                                                 1/1     Running     5          51m
nsm-system    registry-k8s-5446d9b464-ccsb4                               1/1     Running     0          51m
spire         spire-agent-4bchn                                           1/1     Running     0          22h
spire         spire-server-0                                              1/1     Running     0          22h
```

Let me know if you need any logs.

**Comment by Bolodya1997** [comment] 2021-09-17 17:52
@jkossak
> From my observation pods in the spire namespace behave stable (0 restarts) so some times I don't restart it and I encounter the same issues with nsmgr and other nsm pods.

You are totally right - in common there is absolutely no reason for restarting `spire` pods, but this case is caused by SVID update for the `nsm-system` namespace, which keeps happening with 20 minutes period all the time while `spire` pods are working. So restarting `spire` pods in such case can give us more meaningful result of setup failures (or absence of failures).
> @Bolodya1997, after 27 minutes the cross connection stopped working

Are you testing cross connection with `ping` or with `wget`? There is actually one more issue we have noticed during the investigation and it is related to `wget` - https://github.com/networkservicemesh/deployments-k8s/issues/2879.
In short - `wget` periodically works and so periodically stops working. It most probably related to how we set ACL rules in VPP, but it still needs to be further investigated.
So if you are testing it with `wget`, please do it with `ping` - it should be more effective in such case :)
If you are testing connectivity with `ping`, we are most probably missing something, so can you please share `forwarder-vpp` logs in such case?
> I do observe restarts of nsmgr after its termination (OOMKilled)

It is very unexpected that `80Mi` is not enough for the `nsmgr` pod. Can you please set some huge memory limit (e.g. `500Mi` or greater) and share `kubectl top pods` result for it after 30 minutes of running? Or just tell us if it will reach such limit in this time.

I am very sorry for asking you to do such more things, but it looks like we just cannot reproduce all of your behavior locally. So we really need your help to make NSM better :)

**Comment by Bolodya1997** [comment] 2021-09-20 08:52
@jkossak 
There is no more need for this:
> It is very unexpected that 80Mi is not enough for the nsmgr pod. Can you please set some huge memory limit (e.g. 500Mi or greater) and share kubectl top pods result for it after 30 minutes of running? Or just tell us if it will reach such limit in this time.

I can see all NSM applications leaking memory somewhere in gRPC, working on this.

**Comment by jkossak** [comment] 2021-09-29 10:42
Hi @Bolodya1997, please let me know once your fixes are ready so I can test them on our setup .

**Comment by Bolodya1997** [comment] 2021-09-29 12:31
Hi @jkossak, it is almost ready, just waiting for the few last PRs to be merged.
1. PR fixing memory leaks - https://github.com/networkservicemesh/sdk/pull/1090
2. PR tuning memory limits - https://github.com/networkservicemesh/deployments-k8s/pull/2991

Will update you once it will be done.

**Comment by denis-tingaikin** [comment] 2021-09-29 16:00
@jkossak , @Bolodya1997 All PRs merged :) 

@jkossak Be free to re-test this with latest images and let us know about any errors/issues/restarts and so on.

**Comment by jkossak** [comment] 2021-09-30 16:58
Thanks @Bolodya1997 for the update.
I tested the example with all the latest changes on our setup and it is far more stable. Although, there are still some restarts visible - mainly related to nsmgr.  Even with the restarts the cross connection was working for almost two hours, but eventually crashed and then other pods started crashing more often. This is how it looks now:

```
ns-dsq82      nsc-kernel-67fb9f5845-95d8v                                 1/1     Running     5          157m
ns-dsq82      nse-firewall-vpp-76b6968fd7-26h7k                           1/1     Running     0          157m
ns-dsq82      nse-kernel-86f6754c7f-4tqxb                                 1/2     OOMKilled   5          157m
ns-dsq82      nse-passthrough-1-7fb5747798-fr9rk                          1/1     Running     0          157m
ns-dsq82      nse-passthrough-2-c4b677487-jwdv2                           1/1     Running     0          157m
ns-dsq82      nse-passthrough-3-6fdb9c4556-rgd9p                          1/1     Running     0          157m
nsm-system    admission-webhook-k8s-799d79797b-p2jsk                      1/1     Running     0          170m
nsm-system    forwarder-vpp-srhxp                                         1/1     Running     1          170m
nsm-system    nsmgr-cfvfp                                                 1/1     Running     12         170m
nsm-system    registry-k8s-8c984bb57-2l4ld                                1/1     Running     0          170m
```
Here are the logs. Let me know if you need something more.

[nse-firewall-vpp.log](https://github.com/networkservicemesh/deployments-k8s/files/7261220/nse-firewall-vpp.log)
[nsc-kernel.log](https://github.com/networkservicemesh/deployments-k8s/files/7261222/nsc-kernel.log)
[nse-kernel-1.log](https://github.com/networkservicemesh/deployments-k8s/files/7261224/nse-kernel-1.log)
[nse-kernel-2.log](https://github.com/networkservicemesh/deployments-k8s/files/7261225/nse-kernel-2.log)
[nsmgr-1.log](https://github.com/networkservicemesh/deployments-k8s/files/7261228/nsmgr-1.log)
[nsmgr-2.log](https://github.com/networkservicemesh/deployments-k8s/files/7261229/nsmgr-2.log)

**Comment by Bolodya1997** [comment] 2021-10-04 10:32
@jkossak 
Looks like we most probably need different memory limits for the different environment. Can you please run example without any memory limits, so we will be able to measure requirements for your setup?

Steps:
1. Checkout this version of deployments - https://github.com/Bolodya1997/deployments-k8s/tree/test-composition.
2. Start NSE composition example.
3. Leave it for 2 hours.
4. Capture pods used memory info with `kubectl top pods --all-namespaces | grep -v kube-system`.
5. Capture local NSMgr heap profile data:
    1. Run in separate bash session: `kubectl port-forward -n nsm-system pod/${local-nsmgr-pod-name} 9090:9090`.
    2. Run `go tool pprof http://localhost:9090/debug/pprof/heap` - it should create `.pb.gz` file.
    3. Stop [i].
6. Capture remote NSMgr heap profile data.
   1. ...

**Comment by jkossak** [comment] 2021-10-08 11:25
@Bolodya1997  today I noticed few restarts of nsmgr  happened in the same deployment (without memory limit). Nevertheless the cross connection seems to be working fine at the moment.

```
ns-htq7l      nsc-kernel-c68b874d6-cwznk                                  1/1     Running     0          23h
ns-htq7l      nse-firewall-vpp-787cdd5468-lzdkz                           1/1     Running     0          23h
ns-htq7l      nse-kernel-86f6754c7f-ldt5x                                 2/2     Running     0          23h
ns-htq7l      nse-passthrough-1-c7989fbdc-drrr4                           1/1     Running     0          23h
ns-htq7l      nse-passthrough-2-59f8cdc96b-l2td6                          1/1     Running     0          23h
ns-htq7l      nse-passthrough-3-6844c9998f-9hxcv                          1/1     Running     0          23h
nsm-system    admission-webhook-k8s-799d79797b-mzg82                      1/1     Running     0          23h
nsm-system    forwarder-vpp-cbdlf                                         1/1     Running     0          23h
nsm-system    nsmgr-njs28                                                 1/1     Running     4          23h
nsm-system    registry-k8s-749fd78b8b-mk8n6                               1/1     Running     0          23h
```

Here is the output from: kubectl describe pod nsmgr-njs28 -n nsm-system
[describe_nsmgr_pod.txt](https://github.com/networkservicemesh/deployments-k8s/files/7310805/describe_nsmgr_pod.txt)

The output does not mention OOMKilled in termination reason.

I will provide the logs soon.

**Comment by Bolodya1997** [comment] 2021-10-08 11:46
@jkossak
Looks like the reason of the restarts is related to liveness probe failed, we already have an issue for this in backlog (https://github.com/networkservicemesh/deployments-k8s/issues/2766). So currently we want to measure memory limits on your setup to become sure that we will cover it in deployments :)

**Comment by jkossak** [comment] 2021-10-08 11:50
@Bolodya1997 sure, I will retry with https://github.com/Bolodya1997/deployments-k8s/tree/test-composition,  leave it running for the weekend and let you know on Monday the results.

**Comment by Bolodya1997** [comment] 2021-10-12 09:57
@jkossak 
Your logs are very helpful, thank you!
High memory usage in client is unexpected and unfortunately I haven't add `pprof` in client deployment I have provided. But it looks like I can reproduce this on my local single node setup, so this is currently in progress.

**Comment by Bolodya1997** [comment] 2021-11-01 07:23
@jkossak, have you tried to rerun the test again? Is it an every-time failure or it can probably be a some intermittent error?

I am not able to reproduce this issue locally, mostly it looks like some invalid behavior of the web server used in the admission webhook. If it is a first and only test run on the new branch, can you please retry the test? If not, please tell me and we will continue trying to figure out the cause.

**Comment by jkossak** [comment] 2021-11-02 10:19
@Bolodya1997 , yes I tried to rerun the test many times now, from different branches, also  https://github.com/Bolodya1997/deployments-k8s/tree/test-composition and test-composition-new - always the same result.

**Comment by denis-tingaikin** [comment] 2021-11-22 10:50
The initial problem with pings after long NSM running is solved.

We also found a few issues that we'll consider separately.

1. ticket for cmd-exclude-prefixes-k8s  https://github.com/networkservicemesh/cmd-exclude-prefixes-k8s/issues/64
2. ticket for probes: https://github.com/networkservicemesh/deployments-k8s/issues/2766


@jkossak Many thanks for testing this. It was a super useful contribution for us.

Be free to open new issues if you face something unexpected :)

**Closed by denis-tingaikin** 2021-11-22 10:50 UTC
Labels: performance
